version: "3"

services:
  drupal:
    image: drupal:9.3.12-apache-buster
    container_name: drupal
    hostname: drupal.local
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0.28-debian
    container_name: db
    hostname: db.local
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  db-data: